services:
  postgres:
    image: postgis/postgis:15-3.4
    container_name: currijobs_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
      POSTGRES_DB: currijobs
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  postgrest:
    image: postgrest/postgrest:v12.0.2
    container_name: currijobs_postgrest
    depends_on:
      - postgres
    environment:
      PGRST_DB_URI: postgres://devuser:devpassword@postgres:5432/currijobs
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: devuser
      PGRST_OPENAPI_SERVER_PROXY_URI: http://localhost:3000
    ports:
      - '3000:3000'

volumes:
  pgdata:


