
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    prefer_const_constructors: true
    prefer_final_fields: true
    prefer_final_locals: true
    avoid_print: true
